### ISSUE TITLE
Question about running code of deform_conv part

### ISSUE THREAD

**Issue by satchmo233** [tnmichael309/kaggle-nuclei-segmentation#1]
I just want to know did you run the 'deform_conv' part successfully?  how can i get off keras,and embedding the deform_conv layer in the resnet101?

**Comment by tnmichael309** [comment]
If you don't want to use it, you could simply use mask rcnn from model.py instead of model_deform_conv.py (model.py is where most other codes developed: https://github.com/tnmichael309/kaggle-nuclei-segmentation/blob/master/Mask_RCNN/model.py)

To experiment with deform:

import model_deform_conv as modellib

see identity_block\conv_block\resnet_graph in:
https://github.com/tnmichael309/kaggle-nuclei-segmentation/blob/master/Mask_RCNN/model_deform_conv.py

which uses ConvOffset2D implementation in :
https://github.com/tnmichael309/kaggle-nuclei-segmentation/blob/master/Mask_RCNN/deform_conv.py

**Comment by satchmo233** [comment]
Thanks for you help! Now I have knew how to change resnet and embed the deform_conv layer in it,after research you code.     I really appreciate you very much.
